DROP TABLE IF EXISTS `resources`;
DROP TABLE IF EXISTS `boards`;
DROP TABLE IF EXISTS `rappgroups`;

CREATE TABLE `boards` (
  `ID` bigint(20) NOT NULL,
  `NAME` varchar(20) NOT NULL,
  `RAPPGROUP_ID` bigint(20) NOT NULL,
  `DOWNLOAD_KEY` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `rappgroups` (
  `ID` bigint(20) NOT NULL,
  `NAME` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `resources` (
  `ID` int(11) NOT NULL,
  `BOARD_ID` bigint(20) DEFAULT NULL,
  `RAPPGROUP_ID` bigint(20) NOT NULL,
  `DATA` longblob NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `boards`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `NAME` (`NAME`,`RAPPGROUP_ID`),
  ADD KEY `RAPPGROUP_ID` (`RAPPGROUP_ID`);


ALTER TABLE `rappgroups`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `NAME` (`NAME`);


ALTER TABLE `resources`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `BOARD_ID_2` (`BOARD_ID`,`RAPPGROUP_ID`),
  ADD KEY `RAPPGROUP_ID` (`RAPPGROUP_ID`),
  ADD KEY `BOARD_ID` (`BOARD_ID`) USING BTREE;


ALTER TABLE `boards`
  MODIFY `ID` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `rappgroups`
  MODIFY `ID` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `resources`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `boards`
  ADD CONSTRAINT `boards_ibfk_1` FOREIGN KEY (`RAPPGROUP_ID`) REFERENCES `rappgroups` (`ID`);


ALTER TABLE `resources`
  ADD CONSTRAINT `resources_ibfk_1` FOREIGN KEY (`RAPPGROUP_ID`) REFERENCES `rappgroups` (`ID`),
  ADD CONSTRAINT `resources_ibfk_2` FOREIGN KEY (`BOARD_ID`) REFERENCES `boards` (`ID`);

